### ISSUE TITLE
Cannot import obfuscated password from oscrc

### ISSUE THREAD

**Issue by zzndb** [SUSE/open-build-service-connector#16]
Seems we current only can import plain text password from oscrc file. And no any password asking because we already got a obfuscated one?

---

the format of pass related part in my oscrc
```
pass=QlpoOTFBWSZTWRMkfNMAAAaPgBgABUAooAAgQoAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
credentials_mgr_class=osc.credentials.ObfuscatedConfigFileCredentialsManager
```

**Comment by dcermak** [comment]
Indeed, I have not implemented this yet. Same thing will happen if you have your obs password saved in the libsecret keyring. Extracting the obfuscated password shouldn't be too hard though.

**Comment by dcermak** [comment]
This should be fixed in the next release of the extension.
