### ISSUE TITLE
Cannot setup an account on KDE

### ISSUE THREAD

**Issue by doccaz** [SUSE/open-build-service-connector#18]
Freshly installed VSCode with other extensions working, on openSUSE Leap 15.2 with KDE Plasma.
When I install the OBS connector, it asks to import my oscrc, asks for a password... then nothing. The 3 containers on the left are empty. Selecting the "+ Bookmark a Project" will give me a warning that there are no accounts.

If I press Ctrl Shift P and run the "Add an existing account from the Open Build Service to the extension" command, I get prompted for all the values... then I get this:
```
Command 'Add an existing account from the Open Build Service to the extension' resulted in an error (The name org.freedesktop.secrets was not provided by any .service files)
```

This DBUS service is provided by gnome-keyring only.

**Comment by dcermak** [comment]
I am afraid there is nothing I can do here: neither KWallet nor KSecretService implement the secret-service DBUS provider which is used by node-keytar that we use for secret storage (see https://github.com/atom/node-keytar/issues/74).

Unfortunately, you'll have to either install gnome-keyring or keepassx to get a working secret storage. Supporting KWallet itself is far beyond the scope of this plugin (and also not really a good idea imho, because it's in maintenance mode and shall eventually be replaced by KSecretService that will support the secret-storage dbus API, eventually, once it's done…).

**Comment by rdricco** [comment]
> I am afraid there is nothing I can do here: neither KWallet nor KSecretService implement the secret-service DBUS provider which is used by node-keytar that we use for secret storage (see [atom/node-keytar#74](https://github.com/atom/node-keytar/issues/74)).
> 
> Unfortunately, you'll have to either install gnome-keyring or keepassx to get a working secret storage. Supporting KWallet itself is far beyond the scope of this plugin (and also not really a good idea imho, because it's in maintenance mode and shall eventually be replaced by KSecretService that will support the secret-storage dbus API, eventually, once it's done…).

@dcermak Just installing keepassx will work or do I need any additional config? I'm on Manjaro and still cannot start mailspring.

**Comment by dcermak** [comment]
> @dcermak Just installing keepassx will work or do I need any additional config? I'm on Manjaro KDE and still cannot start mailspring.

You do realize that this is neither the mailspring nor the keepassxc issue tracker/FAQ :wink:?
I have never used Keepassxc, so I can only quote what I found in this FAQ: https://github.com/vladimiry/ElectronMail/wiki/FAQ (section "Why automatic login into the app doesn't work on Linux"):

> If you go with KeePassXC here is how to enable the Secret Service support:
>
>    Tools => Settings => Secret Service Integration => check the Enable KeePassXC Freedesktop.org Secret Service Integration checkbox.
>    Database => Database Settings => select the passwords group that will be exposed.

I hope that these instructions are still valid. If not, I'd suggest to ask in the KeepassXC irc/matrix channels ([`#keepassxc:matrix.org`](https://app.element.io/#/room/!zUxwGnFkUyycpxeHeM:matrix.org) or `#keepassxc` on freenode).
