### ISSUE TITLE
adding existing account fails

### ISSUE THREAD

**Issue by jmcdough** [SUSE/open-build-service-connector#28]
Issue Type: <b>Bug</b>

After installing the extension, I use the command to add an existing account to the extension, and I get the result 

Command 'Add an existing account from the Open Build Service to the extension' resulted in an error (command 'vscodeObs.obsAccount.newAccountWizard' not found)

vscode v0.2.24, extension v0.0.5, tumblweed 20210128

Extension version: 0.0.5
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.10.9-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3761)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|23.38GB (0.69GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by dcermak** [comment]
Do you have libsecret installed and is your keyring unlocked? Also, could you try updating to a more recent version of vscode? 1.47.2 is pretty old at this point.

**Comment by jmcdough** [comment]
Bah, I'm terribly sorry, it looks like my upgrade to 1.53.0 had failed but I hadn't noticed it.

However, I've upgraded now and have the same error.  I have libsecret-1-0 installed, and my keyring is unlocked.

**Comment by jmcdough** [comment]
Ok, I've logged out, logged in, ensuring everything is up to date and unlocked, and it worked this time.  Sorry for the noise!

**Comment by dcermak** [comment]
> Ok, I've logged out, logged in, ensuring everything is up to date and unlocked, and it worked this time.  Sorry for the noise!

No problem and glad that it worked out!
